"""
Agent-authored tool: codebase_map

Instant self-awareness of VaultBot's own source. Reads a pre-generated
codebase map note (produced by the Codebase-Map procedure) and returns the
full map or a single module's section in one call — no LLM, no embeddings,
no per-file code_read round-trips.

The map note lives at ``vaultbot/Knowledge/Architecture/Codebase-Map.md``
and is regenerated on demand by the Codebase-Map procedure. This tool is the
READ side: it loads the map so the agent can "understand any part of its own
code in an instant" before editing it.

WHY A NOTE + TOOL (not just a procedure)
----------------------------------------
The Codebase-Map procedure *generates* the map (AST walk, deterministic).
This tool *reads* it back instantly. Separating generate from read means the
agent can regenerate the map rarely (it changes only when the code changes)
but read it cheaply on every turn that touches code.
"""

SCHEMA = {
    "name": "codebase_map",
    "description": (
        "Read VaultBot's own codebase map — a structured index of every "
        "backend module with its purpose, key functions/classes, and imports. "
        "Returns the full map, or a single module's section if 'module' is "
        "given. Use this to instantly understand any part of VaultBot's own "
        "code before editing it, instead of reading files one by one. The map "
        "is generated by the Codebase-Map procedure; if it's missing or stale, "
        "run that procedure first."
    ),
    "parameters": {
        "type": "object",
        "properties": {
            "module": {
                "type": "string",
                "description": (
                    "Optional module name (e.g. 'chat_handler') to return just "
                    "that module's section. Omit for the full map."
                ),
            },
        },
    },
}


def run(args: dict) -> dict:
    """Read the codebase map note and return it (full or per-module)."""
    from pathlib import Path

    # Resolve the map note path relative to the vault root.
    # custom_tools/codebase_map.py -> vaultbot_backend -> vaultbot -> vault root.
    backend_dir = Path(__file__).resolve().parent.parent
    vault_root = backend_dir.parent.parent
    map_path = (
        vault_root / "vaultbot" / "Knowledge" / "Architecture" / "Codebase-Map.md"
    )

    if not map_path.exists():
        return {
            "error": (
                "Codebase map not found. Run the Codebase-Map procedure first "
                "to generate it."
            ),
            "expected_path": str(map_path),
        }

    try:
        text = map_path.read_text(encoding="utf-8", errors="replace")
    except Exception as e:  # noqa: BLE001 — best-effort, returns error to caller
        return {"error": f"Failed to read codebase map: {e}"}

    module = (args.get("module") or "").strip()

    if not module:
        return {
            "status": "success",
            "module": None,
            "content": text,
            "total_chars": len(text),
        }

    # Extract a single module's section. The map uses "## <module>" headers.
    # Find the header for the requested module and slice to the next header.
    lines = text.splitlines()
    header = f"## {module}"
    start = None
    for i, line in enumerate(lines):
        if line.strip() == header or line.strip().startswith(f"## {module} "):
            start = i
            break
    if start is None:
        return {
            "error": f"Module '{module}' not found in codebase map.",
            "available_hint": "Run codebase_map with no 'module' to see the full map.",
        }

    end = len(lines)
    for j in range(start + 1, len(lines)):
        if lines[j].startswith("## "):
            end = j
            break

    section = "\n".join(lines[start:end])
    return {
        "status": "success",
        "module": module,
        "content": section,
        "total_chars": len(section),
    }
